export const GLOBAL_BANKS = [
  // BRASIL - Tradicionais
  { name: 'Itaú Unibanco', code: '341', color: 'bg-orange-500' },
  { name: 'Bradesco', code: '237', color: 'bg-red-600' },
  { name: 'Santander Brasil', code: '033', color: 'bg-rose-600' },
  { name: 'Banco do Brasil', code: '001', color: 'bg-yellow-400' },
  { name: 'Caixa Econômica Federal', code: '104', color: 'bg-blue-600' },
  { name: 'Safra', code: '422', color: 'bg-amber-700' },
  { name: 'Banrisul', code: '041', color: 'bg-blue-800' },
  { name: 'Banco do Nordeste', code: '004', color: 'bg-emerald-700' },
  { name: 'Banco da Amazônia', code: '003', color: 'bg-green-700' },
  
  // BRASIL - Digitais
  { name: 'Nubank', code: '260', color: 'bg-purple-600' },
  { name: 'Inter', code: '077', color: 'bg-orange-600' },
  { name: 'BTG Pactual', code: '208', color: 'bg-slate-900' },
  { name: 'C6 Bank', code: '336', color: 'bg-zinc-900' },
  { name: 'XP Investimentos', code: '102', color: 'bg-slate-800' },
  { name: 'Banco Pan', code: '623', color: 'bg-sky-600' },
  { name: 'Banco Original', code: '212', color: 'bg-emerald-600' },
  { name: 'Neon', code: '000', color: 'bg-cyan-500' },
  { name: 'Next', code: '000', color: 'bg-green-500' },
  { name: 'Digio', code: '000', color: 'bg-blue-900' },
  { name: 'Mercado Pago', code: '323', color: 'bg-sky-400' },
  { name: 'PagBank', code: '290', color: 'bg-emerald-500' },
  
  // ESTADOS UNIDOS & INTERNACIONAIS
  { name: 'JPMorgan Chase', code: 'JPM', color: 'bg-blue-900' },
  { name: 'Wells Fargo', code: 'WF', color: 'bg-red-700' },
  { name: 'Bank of America', code: 'BOA', color: 'bg-blue-700' },
  { name: 'Citibank', code: 'CITI', color: 'bg-blue-500' },
  { name: 'Goldman Sachs', code: 'GS', color: 'bg-slate-700' },
  { name: 'Morgan Stanley', code: 'MS', color: 'bg-blue-950' },
  { name: 'HSBC', code: 'HSBC', color: 'bg-red-600' },
  { name: 'Barclays', code: 'BARC', color: 'bg-sky-800' },
  { name: 'Deutsche Bank', code: 'DB', color: 'bg-blue-800' },
  { name: 'BNP Paribas', code: 'BNP', color: 'bg-emerald-600' },
  { name: 'Société Générale', code: 'SG', color: 'bg-red-600' },
  { name: 'UBS', code: 'UBS', color: 'bg-zinc-800' },
  { name: 'Credit Suisse', code: 'CS', color: 'bg-blue-900' },
  { name: 'Revolut', code: 'REV', color: 'bg-zinc-900' },
  { name: 'N26', code: 'N26', color: 'bg-emerald-900' },
  { name: 'Wise', code: 'WISE', color: 'bg-lime-500' },
  { name: 'PayPal', code: 'PAY', color: 'bg-blue-600' },
  { name: 'Stripe', code: 'STR', color: 'bg-indigo-600' },
];
